export const MAP_COLORS = {
  ground: '#c9e0b4',
  forest: '#a8c88c',
  scrub: '#bed49e',
  grass: '#cce4aa',
  meadow: '#d3e8ae',
  farmland: '#eee9b5',
  urban: '#e4e8dc',
  commercial: '#e9e9e0',
  industrial: '#e0e4dd',
  park: '#bfdda0',
  water: '#7fc4d6',
  waterEdge: '#5d9fb3',
  road: '#f7f5ee',
  roadCasing: '#adb8af',
  building: '#fffdf8',
  buildingAlt: '#f6f3ec',
  buildingBand: '#dedad1',
  label: '#30495b',
  labelHalo: '#fbfcf5',
  transitBlue: '#1769e8',
  sun: '#fff5dc',
  ambientSky: 0xfff7e8,
  ambientGround: 0x8a9b7f,
  shadow: '#4b5d52',
} as const;
